version: '2.1'

services: 
    app:
        build: .
        restart: always
        depends_on:
            - postgres
        ports: 
            - "5005:5005"
        environment: 
            - SQLALCHEMY_DATABASE_URI=${DATABASE_URI}
            - SECRET_KEY=${SECRET_KEY}
    
    postgres:
        image: postgres:10
        restart: always
        ports: 
            - "5432:5432"
        environment: 
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}